# 🤖 Numpy
---
Numpy es una librería de Algebra Lineal en Python. Resulta central para el análisis de datos y aplicaciones estadísticas basicamente porque **casi todas las librerías de Datos del ecosistema Python se basan en numpy**. 

Para más informaciónle recomendamos [Numpy.org - Learn](https://numpy.org/learn/)

![texto alternativo](https://i0.wp.com/www.ozgurozkok.com/wp-content/uploads/2019/12/numpy-python.png?fit=765%2C306&ssl=1)

---
**Autores de la Notebook:** 


* [Matias Sanchez Gavier ](https://matias-online.netlify.app/)  🧛
*   [Matias Moris](https://www.linkedin.com/in/matias-moris-6041337b/) ⚽
* [Anotonio Marrazzo](https://www.linkedin.com/in/antonio-marrazzo-40b3491a2/) 🏆

---

# 👮‍♂️ Numpy Arrays 

El módulo array define una estructura de datos que se parece mucho a list, excepto que todos los miembros tienen que ser del mismo tipo primitivo (todos numéricos)

In [ ]:
# importamos la libreria Numpy
import numpy as np

Podemos crear un array directamente convirtiendo una lista o serie de listas. 

In [ ]:
# lista
a = [1, 2, 3 ]

# array 
np.array(a)

array([1, 2, 3])

## 🤸‍♂️ Shape
---
Este es un método que te permite ver las dimensiones del array.

Devuelve una tuple -> filas, columnas

In [ ]:
mi_matriz = [[1, 2, 3], 
             [4, 5, 6], 
             [7, 8, 9],
             [15,16,48]]

A  = np.array(mi_matriz)

print(A, "\n")

print(A.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [15 16 48]] 

(4, 3)


## 🚣‍♂️ Métodos para Crear Arrays 
---

Los métodos que vamos a ver son:
- np.arange() # Equispaciados enteros
- np.linspace() # Equispaciados reales
- np.zeros() # Matriz de ceros
- np.ones()  # Matriz de unos
- np.eye()  # Matriz de identidad
- np.rand() # Aleatoria uniforme
- np.randn() # Aleatoria normal Estandar

### 👨‍💼 Arange
---
Devuelve valores equiespaciados en un intervalo 

**np.arange(start, stop, step)**


In [ ]:
np.arange(20,53) #no incluye el último 

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### 🚛 linspace
---
Podemos indicar la cantidad de números intermedios con el parámetro num. 

**np.linspace(strat, stop, num)**


In [ ]:
a = np.linspace(20, 30, 20)

In [ ]:
# Aplicaciónen funciones x^2 + 2x +3
def f(x):
  return x**2 +2*x +3

f(a)

array([443.        , 465.38227147, 488.31855956, 511.80886427,
       535.8531856 , 560.45152355, 585.60387812, 611.31024931,
       637.57063712, 664.38504155, 691.7534626 , 719.67590028,
       748.15235457, 777.18282548, 806.76731302, 836.90581717,
       867.59833795, 898.84487535, 930.64542936, 963.        ])

### 🕵️‍♂️ Matriz de Ceros y Unos
---
**np.zeros((filas,columnas))**

**np.ones((filas, columnas))**

In [ ]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 🧘‍♂️ Matriz Identidad
---
La matriz identidad es cuadrada, por ende solo hay que indicar la cantidad de filas.

**np.eye(filas)**


In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### 🧞‍♂️  Arrays aleatorias
---
Hay diversas formas de crear arrays aleatorios

#### 🚁 rand
---
Devuelve arrays con valores aleatorios de una distribución uniforme sobre [0, 1)

In [ ]:
np.random.rand(3)

array([0.14349481, 0.66291496, 0.03725507])

In [ ]:
np.random.rand(4,4)

array([[0.93572302, 0.46559427, 0.16707372, 0.9214074 ],
       [0.07051984, 0.67611158, 0.59067892, 0.76426263],
       [0.14943689, 0.14794358, 0.38913593, 0.79153957],
       [0.28688379, 0.8126091 , 0.58774232, 0.41254027]])

#### 🚉 randn
----
Devuelve arrays con valores aleatorios de una distribución normal estándar

In [ ]:
np.random.randn(3)

array([-0.83109874,  0.57323351, -2.2130809 ])

In [ ]:
np.random.randn(2,2)

array([[-0.06038959, -0.18851773],
       [ 1.48642566, -0.3391319 ]])

## 🦸‍♂️ Indexación y selección en Numpy
---
Refiere a cómo seleccionar un elemento o grupo de elementos de un array. Es parecido a la selección de listas. 

En general es:

**Matriz[Filas, columnas]**

In [ ]:
B = np.arange(0, 10)
B

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
B[5]

5

In [ ]:
B[1:6]

array([1, 2, 3, 4, 5])

In [ ]:
B[0:5] = 100
B

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [ ]:
# ¡Ahora con matrices! 
np.random.seed(100)

matrix = np.random.randn(4,4)
matrix

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114]])

In [ ]:
matrix[0, :]

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604])

In [ ]:
matrix[3,0]

-0.5835950503226648

In [ ]:
matrix[:2, 1:]

array([[ 0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.51421884,  0.22117967, -1.07004333]])

#### 🧟‍♂️ Selección Condicionada
---

La función **np.where(condicion)**, devuelve los índices donde se cumplen la condición.




In [ ]:
A = np.array([
[1, 2, 3],
[4, 5, 6]]) 


#Devuelve indices donde se cumple condición 
mask = np.where(A>4)
print("Mascara: \n", mask)

#Subselección
print("\nSubselección: ")
A[mask]


Mascara: 
 (array([1, 1], dtype=int64), array([1, 2], dtype=int64))

Subselección: 


array([5, 6])

Tambíen podemos hacer cambios en base a la condición

**np.where(condicion, si verdadero, si falso)**}

In [ ]:
np.where(A>4, "Soy Grande" ,"Soy chiquito")

array([['Soy chiquito', 'Soy chiquito', 'Soy chiquito'],
       ['Soy chiquito', 'Soy Grande', 'Soy Grande']], dtype='<U12')

In [ ]:
# otro método de seleción condicionada 
A[A>4]

array([5, 6])


## 🌌  Métodos Summary
Se trata de métodos para encontrar los máximos y mínimos dentro de un array, así como el lugar donde están ubicados


In [ ]:
# Seed para mantener el mismo resultado
np.random.seed(100)

# Matriz Aleatoria Normal
A = np.random.randn(4,2)
A

array([[-1.74976547,  0.3426804 ],
       [ 1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884],
       [ 0.22117967, -1.07004333]])

In [ ]:
print(A)

print("\n Máximo: ")
print(A.max()) #Máximo de toda la array

print("\n Mínimo")
print(A.min()) #Mínimo de toda la array

print("\n Indice del Máximo por columna")
print(A.argmax(axis=0)) # índice del máximo, por columna

print("\n Inidece del Mínimo por columna")
print(A.argmin(axis=0)) # índice del mínimo, por columna

[[-1.74976547  0.3426804 ]
 [ 1.1530358  -0.25243604]
 [ 0.98132079  0.51421884]
 [ 0.22117967 -1.07004333]]

 Máximo: 
1.153035802563644

 Mínimo
-1.7497654730546974

 Indice del Máximo por columna
[1 2]

 Inidece del Mínimo por columna
[0 3]


In [ ]:
print("\n Media:")
print(A.mean()) #Media general

print("\n Media por columna:")
print(A.mean(axis=0)) #Media por columna

print("\n Desvío General:")
print(A.std())

print("\n Desvío por columna:")
print(A.std(axis=1))


 Media:
0.01752383291422248

 Media por columna:
[ 0.1514427  -0.11639503]

 Desvío General:
0.9348256913327037

 Desvío por columna:
[1.04622294 0.70273592 0.23355097 0.6456115 ]


### 🚨 Matriz de Covarianza
---
Se define para un vector de variables aleatorias, en caso de dos variables aleatorias:

$$ \begin{bmatrix}
X \\
Y 
\end{bmatrix}$$

La matriz de covarinaza es una matriz simétrica $\Sigma$: 
$$\Sigma = \begin{pmatrix}
Cov(X,X) & Cov(X,Y) \\
Cov(Y,X) & Cov(Y,Y) 
\end{pmatrix} $$

Recordemos que la covarinza con de una variable con si mismo es su varianza:



$$Cov(X,X) = Var(X)$$

In [ ]:
# Variable X, muestra de una normal
X = np.random.randn(12)

# variable Y, función de X
Y = np.array([2*x+3 for x in X])

# Estimación de matriz de covarianza
np.cov(X,Y)

array([[1.48409633, 2.96819267],
       [2.96819267, 5.93638533]])

##  💾 Ordenar los Array 
---

Podemos usar la función **np.sort(array , axis= )**




In [ ]:
np.random.seed(10)
A = np.random.randint(0,10, size=(4,3) )

print(A, "\n")
np.sort(A, axis=1)

[[9 4 0]
 [1 9 0]
 [1 8 9]
 [0 8 6]] 



array([[0, 4, 9],
       [0, 1, 9],
       [1, 8, 9],
       [0, 6, 8]])

## 🕍 Cambio de dimensiones
---

Podemos usar el método **.reshape(filas, columnas)** para cambiar las dimensiones de la array.




In [ ]:
np.random.seed(10)
A = np.random.randint(0,10, size=(4,3) )

print(A.reshape(2,6), "\n")

print(A.reshape(4,3))

[[9 4 0 1 9 0]
 [1 8 9 0 8 6]] 

[[9 4 0]
 [1 9 0]
 [1 8 9]
 [0 8 6]]


# 🚔 Algebra Lineal
---


### 🚒Operaciones Aritméticas
---




In [ ]:
A = np.array([
[1, 2, 3],
[4, 5, 6]])


B = np.array([
[1, 2, 3],
[4, 5, 6]])
 
# suma
A+B

# Resta
A-B

array([[0, 0, 0],
       [0, 0, 0]])

### 🚂  Multiplicación de vectores
---

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

# Multiplación Vectores
c = a.dot(b)
print(c)

# Multiplicación 1 a 1
d = a*b
print(d)

14
[1 4 9]


### 🚎 Multplicación de Matrices
---
Recuerden que las matrices tienen que coninicider en dimensiones


![texto alternativo](https://www.mathsisfun.com/algebra/images/matrix-multiply-a.svg)

In [ ]:
A = np.array([
[1, 2, 3],
[4, 5, 6]])


B = np.array([
[1, 2, 3],
[4, 5, 6]])

# Multiplicación de Matrices (Dot Product)
print(A(B.T.dot)) # 2x3 , 3x2 = 2x2

[[14 32]
 [32 77]]
[[ 1  4  9]
 [16 25 36]]


## 🏍 Hadamard Product 
---
Esto es cuando dos matrices de la misma dimension se multiplican element-wise.




![texto alternativo](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [ ]:
A = np.array([
[1, 2, 3],
[4, 5, 6]])

B = np.array([
[1, 2, 3],
[4, 5, 6]])

# Hadamard
A*B


array([[ 1,  4,  9],
       [16, 25, 36]])

## 🛸 Multiplicando Matrices con Vectores
---

En el caso de numpy los vectores  los toma como vectores columna, ejemplo 2x1.


$$\begin{bmatrix}
1 & 2 \\
3 & 4\\
5 & 6\\
\end{bmatrix} \cdot \begin{bmatrix}
0.5\\
0.5\\
\end{bmatrix} = \begin{bmatrix}
1.5\\
3.5\\
5.5\\
\end{bmatrix} $$




In [ ]:
A = np.array([
[1, 2],
[3, 4],
[5, 6]])

# Lo toma como vector columna
B = array([0.5, 0.5])

print(B.shape)

C = A.dot(B) # 3x2 , 2x1

print(C)


(2,)
[1.5 3.5 5.5]


## 🌠 Normas
---
La p-norm es una forma de medir el tamaño de un vector. 


![texto alternativo](https://wikimedia.org/api/rest_v1/media/math/render/svg/9f2d83bfa397bdf021046004b9a365079cab6a22)





In [ ]:
from numpy.linalg import norm

b = np.array([1, 2, 3])

p = 2
norm(b,  2 )

3.7416573867739413

![texto alternativo](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d701fe0bf91b2a4931c5a860855e9bbff4ef0c2)

In [ ]:
from math import inf

# La norma de p = infinito es igual al máximo de los valores
a =  np.array([70, 40, 50])

maxnorm = norm(b, inf)
print(maxnorm)

3.0


## 🌉 Operaciones De Algebra Lineal
---

In [ ]:
from numpy.linalg import inv
from numpy.linalg import det
from numpy.linalg import matrix_rank


A = np.array([
[1, 2],
[3, 4]])


#Transpuesta
print(A.T, "\n")

#Inversa, necesita ser cuardada y full rank
print(inv(A), "\n")

# Traza, suma de Diagonales
print(np.trace(A), "\n")


# Determinante, si es distinto de cero es full rank
print(det(A), "\n") 


# Rank
print(matrix_rank(A))



NameError: ignored

## 🏠 Resolución de Ecuaciones
---
Podemos simbolizar un sistema de ecuaciones con:

$$Ax = b$$

$$ x = A^{-1}b $$



In [ ]:
A= np.array( [[20, 14],
    [3, 4]])

b = np.array([3, 1])

# Obtenemos x
x = inv(A).dot(b)

# Comprobamos 
A.dot(x)

array([3., 1.])

In [ ]:
# Con numpy directamente, Recomendado
x  = np.linalg.solve(A,b)

A.dot(x)

array([3., 1.])

## 🥥 Resolución del Modelo Lineal
---

EL modelo lineal se puede representar como: 
$$ y = \beta_0 + \beta_1 x_1  + \dots + \beta_f x_f   $$


El objetivo es minimizar $L$ respecto ${\beta}$:

 $$ L = \sum_{i=1}^n ( \hat{y} - y)^2$$





Si hacemos el desarrollo en forma matricial y encontramos el mínimo de $L$ respecto a $\beta$, llegamos a :

$$θ = (X^T X)^{-1}X^T Y$$

Donde: 

$$\theta = \begin{bmatrix}
\beta_0\\
\beta_1\\
\vdots\\
\beta_f
\end{bmatrix}    \;\;
Y = \begin{bmatrix}
y_0\\
y_1\\
\vdots\\
y_n
\end{bmatrix}  $$
<br>

y $X$ es matriz donde cada columna es una variable explicativa (la primera son todos uno por $\beta_0$) y cada fila una observación.

**Ejemplo:** Verdadera función 

$$ Y = 3+ 2 \cdot x_1 $$


In [ ]:
from numpy.linalg import inv

X = np.random.randn(30,1) # 1 variable, 30 observaciones
Y = [2*x + 3  for x in X]

# Agregamos columna de Unos
unos = np.ones((30,1))
X = np.hstack((unos, X))
X.shape

# Estimación de Betas
betas = inv((X.T.dot(X))).dot(X.T).dot(Y) 
betas

array([[3.],
       [2.]])

## 🍑 Tópicos Avanzados de Algebra Lineal
---

### 🍿 Singular Value Descompsition
---

Cualquier matríz puede descomponerse en una multiplicación de dos matrices ortogonales (U, V) y una matriz diagonal $\Sigma$. 


$$A = U \cdot \Sigma \cdot V^T $$




In [ ]:
from scipy.linalg import svd

A = np.array([
[1, 2],
[3, 4],
[5, 6]])


# factorizo
U, s, V = svd(A)
print(U, "\n")
print(s, "\n")
print(V)


[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]] 

[9.52551809 0.51430058] 

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


### 🧨 Introducción Tensores
---


In [ ]:
H = np.array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])

print(H.shape, "\n")
print(T)


(3, 3, 3) 

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [ ]:

# data reduction with svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define matrix
A = array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
print(A)
# factorize
U, s, V = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
V = V[:n_elements, :]
# reconstruct
B = U.dot(Sigma.dot(V))
print(B)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]


In [ ]:
# transform
T = U.dot(Sigma)
print(T)
)

[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


## 📦  Matriz Dispersa
---

In [ ]:
from scipy.sparse import csr_matrix

A = array([
[1, 0, 0, 1, 0, 0],
[0, 0, 2, 0, 0, 1],
[0, 0, 0, 2, 0, 0]])


S = csr_matrix(A)
print(S, "\n")

B = S.todense()
print(B)


  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2 

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
