## Clase práctica 1 - Introducción a Python + Numpy

La idea de esta notebook es que puedan utilizarla para prácticar los temas vistos en los primeros dos tópicos de la materia: Introduccion a Python, y Numpy. Cabe aclarar que puede que ciertos ejercicios tengan alguna vuelta de tuerca o no se hayan dado durante las clases, por lo que los alumnos deberan **GOOGLEAR** o encontrar la solución por su cuenta. Aunque no lo parezca, saber googlear. cómo solucionar errores o realizar ciertas tareas es sumamente importante la hora de trabajar con cualquier herramienta de programación.

### Importar librerias necearias

Por el momento sólo necesitaran importar Numpy.


In [2]:
import numpy as np

### 1) Listas

#### 1.1. Crear una Lista que contenga los siguientes valores: 1,2,3,4,5,6,7,8. **Puede ser creada utilizando un codigo normal, o utilizando una funcion de numpy llamda np.arange**.

Llamar a esta lista, lista1.

In [53]:
lista1 = [1, 2, 3, 4, 5, 6, 7, 8] #Manera tradicional
lista1 = np.arange(1,9,1).tolist() #Utilizando np.arange
lista1

[1, 2, 3, 4, 5, 6, 7, 8]

#### 1.2. Traer de la lista sólo los valores 5 y 6 utilizando slicing.

In [54]:
lista1[4:6]

[5, 6]

#### 1.3 Agregar al final de la lista el valor 12.

In [55]:
lista1.append(12)
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 12]

#### 1.4 Agregar a la lista el valor 4.5 y ordenarla para que quede en la posición entre el valor 4 y 5. 

**Pista: Utilizar append y luego sortear la lista**

In [56]:
lista1.append(4.5)

lista2 = np.sort(lista1).tolist()
lista2

[1.0, 2.0, 3.0, 4.0, 4.5, 5.0, 6.0, 7.0, 8.0, 12.0]

#### 1.5 Crear una nueva lista llamada lista3 la cual contenga cada valor de la lista 2 multiplicado por 3.

**Pista:** Se puede hacer con un for loop o utilizando **Listas de comprensión**

In [70]:
lista3 = []

for i in lista2:
    val = i*3
    lista3.append(val)
    
    
print(lista3)

[3.0, 6.0, 9.0, 12.0, 13.5, 15.0, 18.0, 21.0, 24.0, 36.0]


In [71]:
# lista de comprension

lista3_bis = [i*3 for i in lista2]

lista3_bis

[3.0, 6.0, 9.0, 12.0, 13.5, 15.0, 18.0, 21.0, 24.0, 36.0]

#### 1.6 Obtener el valor máximo y minimo de la lista. 

Realizar un print que diga "El valor maximo de la lista es: **valor máximo**, y el valor mínimo de la lista es: **valor mínimo**.

**Pista:** Utilizar funciones de np (max y min para obtener dichos valores).

In [72]:
print("El valor máximo de la lista es: " + str(np.max(lista3)) + " , y el valor mínimo de la lista es: " + str(np.min(lista3)))

El valor máximo de la lista es: 36.0 , y el valor mínimo de la lista es: 3.0


#### 1.7 For loop con condicionales.

Crear una nueva lista llamada lista4, en donde si el número es par sea elevado al cuadrado, y si es impar que el número quede igual. Utilizar como input la lista3.

Es decir, que si mi lista es [1,2,3,4], el output deberia ser [1, 4, 3, 16].

**Usar un for loop**

In [80]:
lista4 = []

for i in lista3:
    if i % 2 == 0:
        val = i**2
    else:
        val = i
    lista4.append(val)
    
lista4

[3.0, 36.0, 9.0, 144.0, 13.5, 15.0, 324.0, 21.0, 576.0, 1296.0]

#### 1.8 For loop con más de un condicional. 

Crear una nueva lista llamada lista5 que sea identica a la lista4, sólo con 2 modificaciones:
- Si el valor de la lista4 es igual a 21, que sea transformado por 100.
- Si el valor de la lista4 es igual a 9, que sea transformado por 200.
- Si el valor de la lista4 no es ni 21 ni 9, que se mantenga el mismo valor.

**Pista:** Utilizar la funcion .index

In [92]:
lista5 = lista4.copy()

for i in lista5:
    if i == 21:
        lista5[lista5.index(i)] = 100
    elif i == 9:
        lista5[lista5.index(i)] = 200
    else:
        pass

lista5

[3.0, 36.0, 200, 144.0, 13.5, 15.0, 324.0, 100, 576.0, 1296.0]

### 2) Diccionarios

#### 2.1) Crear un diccionario con la siguiente información:
- Carrera: Actuario ("string")
- Materias: 34 ("int")
- Tema: Python ("string")
- Cursada: Distancia ("string")

Llamarlo dict1.


In [94]:
dict1 = {"Carrera":"Actuario", 
        "Materias": 34,
        "Tema":"Python",
        "Cursada": "Distancia"}

dict1

{'Carrera': 'Actuario',
 'Materias': 34,
 'Tema': 'Python',
 'Cursada': 'Distancia'}

#### 2.2) Realizar el siguiente print utilizando el diccionario:

"Estudio la carrera de Actuario la cual consta de 34 materias. Actualmente estoy aprendiendo Python a distancia. "

**Utilizar printing avanzado.**

In [96]:
carrera = dict1["Carrera"]
materias = dict1["Materias"]
tema = dict1['Tema']
modalidad = dict1['Cursada']

print("Estudio la carrera de {} la cual consta de {} materias. Actualmente estoy aprendiendo {} a {}.".format(
    carrera, materias, tema, modalidad))


Estudio la carrera de Actuario la cual consta de 34 materias. Actualmente estoy aprendiendo Python a Distancia.


#### 2.3) Agregar una nueva key que sea "Facultad" y contenga el valor "UBA"

In [99]:
dict1['Facultad'] = "UBA"
dict1

{'Carrera': 'Actuario',
 'Materias': 34,
 'Tema': 'Python',
 'Cursada': 'Distancia',
 'Facultad': 'UBA'}

#### 2.4) Crear dos listas, una que contenga las keys y otra que contenga los valores.

Las keys van a ser las mismas que dict1, pero los valores van a ser los siguientes:
- Carrera: se mantiene igual en Actuario.
- Materias: se modifica por el valor "Dos optativas".
- Tema: se modifica por el valor "R".
- Cursada: se modifica por el valor "Virtual".
- Facultad: se mantiene igual.

**Pista**: Para crear la lista de keys pueden utilizar dict.keys().tolist(). Luego creen la otra lista con los nuevos valores, y busquen como usar la funcion dict + zip.

A est enuevo diccionario llamarlo dict2.

In [102]:
nuevas_keys = dict1.keys()
nuevos_valores = ['Actuario', "Dos optativas", "R", "Virtual", "UBA"]

dict2 = dict(zip(nuevas_keys, nuevos_valores))
dict2

{'Carrera': 'Actuario',
 'Materias': 'Dos optativas',
 'Tema': 'R',
 'Cursada': 'Virtual',
 'Facultad': 'UBA'}

### 3) Matrices y arrays

#### 3.1) Crear un array que contenga valores desde 0 a 30, con steps de 2.

Llamar al array array1.

In [106]:
array1 = np.arange(0,31,2)

array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

#### 3.2) Crear una nuevo array llamado array2 en donde si el valor es mayor a 16, se modifique por 20.

In [109]:
array2 = np.where(array1 > 16, 20, array1)
array2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 20, 20, 20, 20, 20, 20, 20])

#### 3.3) Crear una matriz utilizando los array 1 y 2. La matriz debe ser de 2x5.

**Las primera fila debe contener los primeros 5 valores del array 1, y la segunda fila los 5 valores del array2.**

Output seria:

[0, 2, 4, 6, 8]

[20, 20, 20, 20, 20]

Llamarla como matrix1.

**Utilizar slicing de listas**

In [124]:
array1_filtrado = array1[:5]
array2_filtrado = array2[-5:]

matrix1 = np.array([array1_filtrado,
                  array2_filtrado])

matrix1

array([[ 0,  2,  4,  6,  8],
       [20, 20, 20, 20, 20]])

#### 3.4) Para los valores de la primer fila, multiplicarlos por 3.  

Para este ejercicio hay muchas formas de hacerlo. 

**Pista:** Crear un nuevo array con los valores de la primer fila multiplicados por 3, y luego reemplazar la primer fila (matrix[0,:]) por este nuevo array.

In [142]:
matrix1[0,:] = np.array([i*3 for i in matrix1[0,:]])

matrix1

array([[ 0,  6, 12, 18, 24],
       [20, 20, 20, 20, 20]])

#### 3.5) Obtener el valor máximo de cada columna.

Utilizar un for loop e imprimir el valor máximo de cada columna.

In [143]:
for col in np.arange(1, matrix1.shape[1]):
    print("El valor máximo de la columna " + str(col) + " es: " + str(np.max(matrix1[:,col])))

El valor máximo de la columna 1 es: 20
El valor máximo de la columna 2 es: 20
El valor máximo de la columna 3 es: 20
El valor máximo de la columna 4 es: 24
